name: build-docker-image

on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC (12 AM CST)

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          no-cache: true
          tags: coderrect/openrace:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
